Project Work Libreria/Controllers/BookCategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Work_Libreria.Database;
using Project_Work_Libreria.Models;

namespace Project_Work_Libreria.Controllers
{
    public class BookCategoryController : Controller
    {
        [HttpGet]
        public IActionResult Create()
        {
            using (BookShopContext db = new BookShopContext())
            {
                BookCategory data = new();
                return View(data);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BookCategory data)
        {
            using (BookShopContext db = new BookShopContext())
            {

                BookCategory newCategory = new BookCategory();
                newCategory.Name = data.Name;

                db.Categories.Add(newCategory);
                db.SaveChanges();
                return RedirectToAction("Index", "Book");
            }


        }
    }
}

Project Work Libreria/Views/Shared/_Footer.cshtml
<div class="footer mb-0 d-flex justify-content-between">
    <div class="uno">
        <h3 class="philosopher text-black">LINK UTILI</h3>
        <a class="text-black" href="@Url.Action("Index", "Book")">Home</a>
       
    </div>
    <div class="due disappear-on-media">
        <h3 class="philosopher">NEWSLETTER</h3>
        <form>
            <input type="email" placeholder="Inserisci la tua email">
            <br>
            <button type="submit" class="btn btn-lg-r text-white">Iscriviti ora</button>
        </form>
    </div>
    <div class="tre">
        <h3 class="philosopher">DOVE SIAMO</h3>
        <p class="mb-0"> GenerationItaly</p>
    </div>

</div>

Project Work Libreria/Views/Shared/_Header.cshtml
 <!--navbar-->
<nav class=" navbar navbar-expand-lg bg-body-tertiary">
    <div class="container">
        <img src="~/css/PHOTO-2023-06-06-14-34-00-removebg-preview.png" width="65px" height="60px" alt="ladra di libri">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav philosopher">

                <a class="btn btn-lg-n " href="@Url.Action("Index","Book")">HOME</a>

                @if(User.IsInRole("ADMIN")){
                    <a class="btn btn-lg-n" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
                    ADMIN TOOLS
                    </a>
                }
                <div class="my-auto">   <partial name="_LoginPartial" /></div>
             
            
            </div>
        </div>

        <div>
            <h2 class="allura">Generation<span>BookShop</span></h2>
        </div>
    </div>
</nav>

<!--corpo dell'offcanvas-->

<div class="offcanvas offcanvas-start borders" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h3 class="offcanvas-title pt-3 text-white philosopher" id="offcanvasExampleLabel">Gestisci i tuoi libri</h3>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body text-white">


        <ul>

            <a href="@Url.Action("Create","Book")"> 
                <button type="button" class="btn mb-0 text-white philosopher">Aggiungi un libro</button>
            </a>
        </ul>

        <ul>
            <a href="@Url.Action("Create","BookCategory")">
                <button type="button" class="btn mt-3 text-white philosopher">Aggiungi una categoria</button>
            </a>

        </ul>

        <ul>

            <a href="@Url.Action("Admin","Book")">
                <button type="button" class="btn mb-3 text-white philosopher">Vista Gestionale</button>
            </a>
        </ul>
    </div>
</div>

Project Work Libreria/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project_Work_Libreria</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Project_Work_Libreria.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Project_Work_Libreria</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Project_Work_Libreria - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Project Work Libreria/Views/Shared/_MyLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>BookShop</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons+Outlined"
          rel="stylesheet">
    <link rel="apple-touch-icon" sizes="180x180" href="~/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="~/android-chrome-192x192.png">
    <link rel="icon" type="image/png" sizes="16x16" href="~/css/favicon-32x32.png">
    <link rel="manifest" href="/site.webmanifest">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/d2df525ae1.js" crossorigin="anonymous"></script>
    <link href="~/css/site.css" rel="stylesheet" />
</head>
<body class="bg-contrast">
    
    <header>
        @Html.Partial("_Header")
    </header>

    <main>
        @RenderBody()
    </main>

    <footer>
        @Html.Partial("_Footer")
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.7.0.min.js" integrity="sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        @RenderSection("Scripts", required: false)
    </script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
</body>
</html>