Project Work Libreria/Models/PurchaseData.cs
namespace Project_Work_Libreria.Models
{
    public class PurchaseData
    {
        public int Id { get; set; }

        public DateTime PurchaseDate { get; set; }

        public int Quantity { get; set; }





        public int? PurchasedBookId { get; set; }
        public Book? PurchasedBook { get; set; }





    }
}

Project Work Libreria/Controllers/PurchaseDataController.cs
using Microsoft.AspNetCore.Mvc;
using Project_Work_Libreria.Database;
using Project_Work_Libreria.Models;
using Project_Work_Libreria.Models.ModelForViews;

namespace Project_Work_Libreria.Controllers
{
	public class PurchaseDataController : Controller
	{
		[HttpGet]
		public IActionResult Create(int id)
		{
			using (BookShopContext db = new BookShopContext())
			{
				PurchaseData data = new();
				Book book = db.Book.Where(book => book.Id == id).FirstOrDefault();
				PurchaseData_Book modelForView = new();

				modelForView.Book = book;
				modelForView.PurchaseData = data;



				return View(modelForView);
			}
		}

		[HttpPost]
		[ValidateAntiForgeryToken]
		public IActionResult Create(int id, PurchaseData_Book modelForView)
		{
			using (BookShopContext db = new BookShopContext())
			{

				DateTime purchaseDate = DateTime.Now;
				modelForView.PurchaseData.PurchasedBookId = id;
				modelForView.PurchaseData.PurchaseDate = purchaseDate;
				db.PurchaseData.Add(modelForView.PurchaseData);
				Book BoughtBook = db.Book.Where(book => book.Id == id).FirstOrDefault();
				BoughtBook.PurchaseQuantity += modelForView.PurchaseData.Quantity;
				BoughtBook.AvailableCopies = BoughtBook.AvailableCopies - modelForView.PurchaseData.Quantity;
				db.SaveChanges();
				return RedirectToAction("Index", "Book");
			}


		}


	}
}

Project Work Libreria/Views/PurchaseData/Create.cshtml
@using Project_Work_Libreria.Models.ModelForViews;
@model PurchaseData_Book


<div class="container login">
    <div class="border borders rounded-5 mt-5">
         <div class="row">

            <div class="col-sm-12 col-md-6  m-auto">


                <div class="libro">
                    <span></span>
                    <img src="@Model.Book.ImgSource" alt="@Model.Book.Title" />
                </div>


            </div>

            <div id="border" class="col-lg-6 col-md-8 col-sm-6 m-auto my-3 ps-5">
                <h1 class="mb-3 philosopher">Riepilogo acquisto</h1>
                <div class=" p-3">
                  <form asp-controller="PurchaseData" asp-action="Create" method="post" asp-route-id="@Model.Book.Id" class="mt-2  mb-2 py-3">
                    @Html.AntiForgeryToken()
            
              

                    <div class="mb-3">
                        <label asp-for="PurchaseData.Quantity" class="form-label philosopher">Quantità</label>
                        <input asp-for="PurchaseData.Quantity" type="number" class="form-control p-libri " style="width:270px" required>
                        <span asp-validation-for="PurchaseData.Quantity" class="text-danger"></span>
                    </div>

                        <h3 class="philosopher">
                            Titolo:
                        </h3>
                        <p>@Model.Book.Title</p>

                        <h3 class="philosopher">
                            Autore:
                        </h3>
                        <p>@Model.Book.Author</p>

                        <h3 class ="philosopher">
                            Prezzo:
                        </h3>
                        <p> @Model.Book.Price.ToString("n2")</p>




                        <button type="submit" class="btn purchase px-0 btn-n">Acquista</button>
                </form>
                </div>
            </div>
            
            
          </div>
    </div>
</div>